### PR TITLE
habitat model

### PR DESCRIPTION
**Pull request by sylviama**

### CODE REVIEW

**Review by mattbruton — COMMENTED** [review]
Looks good, Sylvia. 👍

**Comment by sylviama** [comment]
I cannot figure out how to solve this conflict, just ignore this branch and create a Habitat model on your branch...@Matt

**Comment by Odigene12** [comment]
👍 Looks good. Once the merge conflicts are fixed, you should be good to merge

**Comment by mattbruton** [comment]
You'd probably have to use VS Code or another text editor to resolve the conflict. Shouldn't be a need to delete entire files as you can pick which version of code you want to keep/reject. If you still want me to, I can add your model in the project.

**Pull request closed without merging**
